### ISSUE TITLE
Remove Guard

### ISSUE THREAD

**Issue by tfausak** [orgsync/stoplight#100]
I don't want to bother dealing with Guard after https://github.com/guard/listen/pull/371.

**Comment by e2** [comment]
I don't want to bother dealing with Ruby < 2.2. Neither does the Ruby core team....

**Comment by tfausak** [comment]
I don't blame you. Dropping support for a version of Ruby is a breaking change. That is a change that should be made as part of a major version change.

**Comment by e2** [comment]
@tfausak - it wasn't about "dropping support". Support was already officially dropped - it was a bug that the dependency wasn't updated.

Also, according to SemVer, what I did was fine.

**Comment by e2** [comment]
Just FWIW: The current release candidate for Bundler resolves this: on 1.9.3 even, it correctly uses a version of Listen installable with Ruby 1.9.3.

All you'd need to do is put `gem install bundler --pre` in your Travis config.
