### ISSUE TITLE
Threshold in percent

### ISSUE THREAD

**Issue by luizkowalski** [orgsync/stoplight#104]
According to the docs, seems like the threshold is based in failed API calls in sequence (e.g. a 3 threshold will trips the circuit after the third call fails). At least is what I understood.
Is it possible to open the circuit after a certain % of calls failed?

**Comment by tfausak** [comment]
This has been requested before. See #86 and #45. If you need this right now, use [Circuitbox](https://github.com/yammer/circuitbox).

**Comment by luizkowalski** [comment]
Cool, thanks!
Also, is there any way to trip the circuit if my API call is slow?
