### ISSUE TITLE
Remove stoplight-admin from README or update stoplight-admin

### ISSUE THREAD

**Issue by bschaeffer** [orgsync/stoplight#113]
There is an issue on orgsync/stoplight-admin#19 that wants to know if 2.1.0 is supported, but hasn't gotten any response at all.

Does the admin interface support the current `2.x` version? If you reference the gem from the README, but it isn't supported by the current stoplight version that references, it should be removed.

**Comment by tfausak** [comment]
Sorry for the radio silence. stoplight-admin hasn't ever been as fully supported as Stoplight itself, hence the 0.x.x version number. Even so, I think the link in the README is fine. I'll merge https://github.com/orgsync/stoplight-admin/pull/20 🙂
