### ISSUE TITLE
V2.1.3 missing Pagerduty Notifier

### ISSUE THREAD

**Issue by ju-Skinner** [orgsync/stoplight#127]
My team is currently using v2.1.3 of your gem and noticed that there is a discrepancy between Master and V2.1.3.

### Gem deployed to `rubygems.org`
![image](https://user-images.githubusercontent.com/1633290/67127143-5b56b480-f1be-11e9-9aca-ce7b926d9196.png)

### What's in master
https://github.com/orgsync/stoplight/blob/master/lib/stoplight.rb#L27

**Comment by bolshakov** [comment]
Yeah, you're right. That's because v2.1.3 way behind of master https://github.com/orgsync/stoplight/compare/v2.1.3...master

**Comment by bolshakov** [comment]
@ju-Skinner I've just released [v2.2.0](https://rubygems.org/gems/stoplight) with Pagerduty support

**Comment by ju-Skinner** [comment]
@bolshakov I noticed that you have taken ownership of this gem. The team I am working on, is curious to know if you will be maintainer going forward. Also, I assume you will be maintaining https://github.com/orgsync/stoplight-admin. If so, thank you so much.

**Comment by bolshakov** [comment]
@ju-Skinner Yeah, I'm maintaining both stoplight and stoplight-admin now.
