### ISSUE TITLE
Green to red transition should be on error % rather than arbitrary number

### ISSUE THREAD

**Issue by clifton** [orgsync/stoplight#45]
```ruby
# request key could be the first 8 chars of the req UUID to start
# later, we could transition to using failures by portal or user id or whatever
def record_success(request_key)
  conn.zadd("#@key-success", Time.now.to_i, request_key)
  cleanup! if rand > 0.98
end

def record_error(request_key)
  conn.multi do
    conn.zadd("#@key-error", Time.now.to_i, request_key)
    @error_cnt = conn.zcount("#@key-error", 2.hours.ago.to_i, Time.now.to_i)
    @success_cnt = conn.zcount("#@key-success", 2.hours.ago.to_i, Time.now.to_i)
    cleanup! if rand > 0.98
  end
  errors, successes = [@error_cnt, @success_cnt].map(&:value)
  transiton_to_red! if errors.to_f / (errors  + successes).to_f > 0.15
end

def cleanup!
  conn.zremrangebyscore(...)
end
```

This could also be done with hashes + counters in one hour groupings where you'd keep the last 3 hours (or some other time period that's sensible) but cleanup would be more difficult.

**Comment by tfausak** [comment]
If we decide to go this route, we could follow Circuitbox's lead.

> Once more than 10 requests have been made with a 50% failure rate, Circuitbox stops sending requests to that failing service for one minute.

https://github.com/yammer/circuitbox/blob/v0.7.0/README.md

**Comment by tfausak** [comment]
For the time being, Stoplight will not support this. If you need this behavior, use [Circuitbox](https://github.com/yammer/circuitbox) instead. If there is enough demand, I will reconsider adding this to Stoplight.
