### ISSUE TITLE
Consider multi_json gem.

### ISSUE THREAD

**Issue by AaronLasseigne** [orgsync/stoplight#65]
https://github.com/intridea/multi_json

It abstracts away the use of a particular JSON gem but allows for use of more gems if they're available. It would add a dependency but it gives stoplight the ability to use something like `oj` which is faster without expressly requiring it.

**Comment by tfausak** [comment]
:+1: This makes a lot of sense.

**Comment by tfausak** [comment]
Switching to Oj didn't noticeably improve performance. I think having no dependencies is better than being a few percent faster in a pathological benchmark.
