### ISSUE TITLE
yellow state?

### ISSUE THREAD

**Issue by jrochkind** [orgsync/stoplight#69]
The README says:

> Stoplights will automatically attempt to recover after a certain amount of time. A light in the red state for longer than the timeout will transition to the yellow state. This timeout is customizable.

But that's the only mention of a "yellow" state, rather than "red" and "green".  What is the yellow state?

**Comment by tfausak** [comment]
Stoplights move into the yellow state after being in the red state for a while. When they're yellow, they'll try to run their code. If that fails, they'll go back to red. If it succeeds, they'll switch to green. 

Does that answer your question? If so, I'll update the readme to say that.

**Comment by jrochkind** [comment]
Yes, that helps, thanks!
