### ISSUE TITLE
Clarify using timeout to disable automatic recovery

### ISSUE THREAD

**Issue by tfe** [orgsync/stoplight#73]
In the readme, it says: "Set the timeout to -1 to disable automatic recovery." Based on this, I would have expected that after enough failures it would remain red indefinitely (i.e. not automatically recover), but this is not the case. It actually goes immediately back to yellow (because it's been longer since the failure than the negative timeout).

Is this a bug or am I just reading it incorrectly?

**Comment by tfausak** [comment]
Thanks for reporting this! It does indeed look like a bug.

``` rb
light = Stoplight('example') { fail }.with_timeout(-1)
light.threshold.times { light.run rescue nil }
light.color
# => "yellow"
```

I think the light should be in the red state at that point, but I'm having a hard time finding a commit where that's the case. Only [one line](https://github.com/orgsync/stoplight/blob/v1.1.1/lib/stoplight/light/runnable.rb#L15) reads the timeout, and it doesn't check for negative values. 

We didn't introduce timeouts in a pull request, so I don't have any discussion to reference. However #37 looks relevant.

**Comment by tfausak** [comment]
As a workaround, you can set the timeout to `Float::INFINITY`.

**Comment by tfausak** [comment]
I think the documentation is inaccurate and should be changed. Instead of recommending `-1` for disabling automatic recovery, it should recommend `Float::INFINITY`. That requires no change to the code and is more intention-revealing at the call site. Consider the following examples:

``` rb
# What does this mean? I'd have to read the documentation to find out.
Stoplight('...') { ... }.with_timeout(-1)
# This is pretty obvious.
Stoplight('...') { ... }.with_timeout(Float::INFINITY)
```

Does this solution work for you?

**Comment by tfe** [comment]
That works for me! Totally agree on the intention-revealingness aspect.
