### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by AndreasWurm** [orgsync/stoplight#87]
Hey,

Stoplight with MemoryStore is not threadsafe. 
It would be awsome if stoplight would be usable in threaded ruby code.
The only shared state between Stoplights seems to be the class variables in Stoplight::Light and the DataStore.

**Comment by tfausak** [comment]
I would like Stoplight to be thread safe, but I don't have a lot of experience with thread safety in Ruby. If I understand you correctly, we would have to do at least two things to make Stoplight thread safe:

- Do something with [these class variables](https://github.com/orgsync/stoplight/blob/v1.2.0/lib/stoplight/light.rb#L26-L33) in `Stoplight::Light`. 

- Do something with [the in-memory data store](https://github.com/orgsync/stoplight/blob/v1.2.0/lib/stoplight/data_store/memory.rb#L6). 

Is that correct?

**Comment by AndreasWurm** [comment]
First off, a bit of clarification why we should care about threadsafety. Its not only about writing concurrent code ourselfs but another important usecase is using threaded libraries or frameworks for example just using Rails in a threaded server, like [Puma](https://github.com/puma/puma) or [Phusion Passenger](https://www.phusionpassenger.com/library/config/apache/reference/#passengerconcurrencymodel) with `PassengerConcurrencyModel thread`.

```ruby
class SomeController < ApplicationController
  def serve
    light = Stoplight('example') do
      # some interaction with active record
      # some interaction with a web service
    end
    light.run
  end
end
```

 * Regarding the class vars we should use a thread safe array for [default_notifiers](https://github.com/orgsync/stoplight/blob/v1.2.0/lib/stoplight/light.rb#L32) for the case that during initialization multiple threads append notifiers.

* regarding the memory store the easiest fix would be to synchronize all methods using a Mutex.
Also the failures array for a light is exposed and mutated in [record_failure](https://github.com/orgsync/stoplight/blob/master/lib/stoplight/data_store/memory.rb#L23), but this can also be easily mitigated. There is probably room for performance improvements over this simple approach.

I'll give it a shot during the next week and come back to you with a suggested implementation.

**Comment by tfausak** [comment]
Ok great! I will be happy to review a pull request. Let me know if I can help.

**Comment by tfausak** [comment]
Any movement on this?

**Comment by AndreasWurm** [comment]
sorry mate havnt found the time yet, this weekend is also pretty stuffed, give me till next friday

**Comment by tfausak** [comment]
No rush.

**Comment by tfausak** [comment]
Did #92 close this, or is there more to do?

**Comment by AndreasWurm** [comment]
think its fine  :thumbsup:

**Comment by tfausak** [comment]
Great, thanks!
