### ISSUE TITLE
Rename timeout?

### ISSUE THREAD

**Issue by tfausak** [orgsync/stoplight#88]
I think the term "timeout" can be confusing. In Ruby, "timeout" most often means [`Timeout.timeout`](http://ruby-doc.org/stdlib-2.3.0/libdoc/timeout/rdoc/Timeout.html#method-c-timeout). In Stoplight, timeouts don't have anything to do with limiting execution time. Instead they have to do with attempting to recover from a red light. 

I don't have any better names for the concept though.

**Comment by zeisler** [comment]
Possible name `cool_off_time`

**Comment by tfausak** [comment]
Fixed by #96.
