### ISSUE TITLE
Long running code changes red stoplight back to green too quickly

### ISSUE THREAD

**Issue by mrdziuban** [orgsync/stoplight#93]
When a long-running block of code is called and the stoplight changes from green to red while that code is still running, it is possible for the failures to be cleared and the stoplight to be changed back to green as soon as the long-running code completes and `run_green` continues executing. Consider the following scenario, which describes a stoplight turning from green to red due to a database concurrency limit:

| Event | Start time | Stoplight color | Stoplight method | Resulting action |
| --- | --- | --- | --- | --- |
| Query 1 starts | 11:00:00 | Green | `run_green` | Query begins |
| Query 2 starts | 11:00:05 | Green | `run_green` | Query is rejected because of the concurrency limit; stoplight switches from green to red |
| Query 1 completes | 11:00:10 | Red | `run_green` (continued from when query 1 started) | Failures are cleared; stoplight switches from red to green |

In this case, the stoplight was only red for 5 seconds, rather than the default timeout of 60 seconds. Additionally, no notifications indicate that the stoplight returned from red to green, because `run_green` does not supply an `on_success` callback.

A possible solution here is to store the color of the stoplight before running the code and only call `clear_failures` after the code finishes executing if the stoplight color has not changed.

**Comment by tfausak** [comment]
Closing due to lack of interest. If this affects you, let me know! Also check out #103 for a potential solution.
